version: '2'

services:
  api:
    build: .   
    environment:
      "MONGO_URI": "mongodb://root:1234@mongo:27117/mobaconanalytic"
    ports:
      - "3001:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    #command: mongod --port 27117
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes: 
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234  
      ME_CONFIG_MONGODB_PORT: 27117
    depends_on:
      - mongo
volumes:
  mongodbdata: