version: '3.1'

services:
  api:
    build: .   
    environment:
      "MONGO_URI": "mongodb://root:1234@mongo:27017/mobaconanalytic"
    ports:
      - "3001:3000"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234